/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.infrastructure.util.StringUtil;
import br.com.ifba.curso.Controller.CursoControllerI;
import br.com.ifba.curso.entity.Curso;
import jakarta.annotation.PostConstruct;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author Casa
 */
@Component
public class CursoListar extends javax.swing.JFrame {

    @Autowired
    public CursoListar(CursoControllerI cursoController) { //removi o construtor padrão porque o spring só faz a injeção de dependências de beans que ele mesmo cria
        this.cursoController = cursoController;
        initComponents();
        tableModel = (DefaultTableModel) tbnCursos.getModel();
        jOptionPane1.setVisible(false);
        carregarDados();
    }

    final DefaultTableModel tableModel;//setar o modele default nas tabelas

    List<Curso> listaCursos = new ArrayList(); //lista para ajudar a popular a tabela

    @Autowired
    CursoControllerI cursoController;// injeção para acesso a camda controlle

    StringUtil stringUtil = new StringUtil();

    int itemSelecionado;

    /**
     * Creates new form CursoListar
     */
    public void desfazerSelecao() {// para melhorar a legibilidade do código

        itemSelecionado = -1;

    }

    public void adicionarCurso(Curso curso) {

        if (curso == null) {

            jOptionPane1.showMessageDialog(null, "Não foi possível adicionar o curso");//

        }

        Curso cursoSalvo = cursoController.save(curso);

        listaCursos.add(cursoSalvo);

        tableModel.addRow(new Object[]{
            cursoSalvo.getNome(),
            cursoSalvo.getId(),
            formatarStatus(cursoSalvo.getAtivo()),
            cursoSalvo.getAlunosMatriculados()
        });

    }
    
    public void editarCurso(Curso cursoEditado) {

        tbnCursos.setValueAt(cursoEditado.getNome(), itemSelecionado, 0);//atualizar     
        tbnCursos.setValueAt(cursoEditado.getId(), itemSelecionado, 1);// a
        tbnCursos.setValueAt(formatarStatus(cursoEditado.getAtivo()), itemSelecionado, 2);// tabela
        tbnCursos.setValueAt(cursoEditado.getAlunosMatriculados(), itemSelecionado, 3);

        listaCursos.set(itemSelecionado, cursoEditado);//atualizo a lista

        cursoController.update(cursoEditado);//joga para a segunda camada 

    }

    public String formatarStatus(boolean status) {//para na tabela nao aparecer 'true' ou 'false'

        if (status) {

            return "Ativo";
        } else {
            return "Inativo";
        }

    }

    public boolean verificarStatusComboBox(javax.swing.JComboBox<String> comboBox) {//refatorei as duas funções em apenas uma

        String selecao = (String) comboBox.getSelectedItem();

        if (selecao.equals("Selecione um status")) {
            jOptionPane1.showMessageDialog(null, "Selecione um status válido");

        } else if (selecao.equals("Ativo")) {

            return true;
        }

        return false;

    }

    public void preencherTabela() { //funcao para não repetir toda vez essas 6 linhas para popular a tabela

        for (Curso curso : listaCursos) {
            tableModel.addRow(new Object[]{
                curso.getNome(),
                curso.getId(),
                formatarStatus(curso.getAtivo()),
                curso.getAlunosMatriculados()
            });
        }

    }

    public void carregarDados() {//puxar dados da classe dao para a view 

        tableModel.setRowCount(0);
        listaCursos.clear();

        List<Curso> listaCapsula = cursoController.findAll();//passando todos os itens do BD  para a lista

        for (Curso curso : listaCapsula) {
            listaCursos.add(curso); //passando todos os itens da lista capsula para a lista local
            preencherTabela();
        }
    }

    public void limparcaixadeTexto(){
    
    txtbarradePesquisa.setText("");
    txtnovaQtdAlunos.setText("");
    txtnovaquantidadeAlunos.setText("");
    txtnovoNome.setText("");
    txtnovonomeCurso.setText("");
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFadicionarCurso = new javax.swing.JFrame();
        txtnovonomeCurso = new javax.swing.JTextField();
        lblnomedoCurso = new javax.swing.JLabel();
        txtnovaquantidadeAlunos = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnconfirmarAdicao = new javax.swing.JButton();
        JFeditarCurso = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        txtnovoNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnovaQtdAlunos = new javax.swing.JTextField();
        cbEditar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbnCursos = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnExcluri = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        txtbarradePesquisa = new javax.swing.JTextField();
        jOptionPane1 = new javax.swing.JOptionPane();

        lblnomedoCurso.setText("Nome do Curso");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um status", "Ativo", "Inativo" }));

        jLabel1.setText("Quantidade de alulnos");

        btnconfirmarAdicao.setText("Adicionar");
        btnconfirmarAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmarAdicaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JFadicionarCursoLayout = new javax.swing.GroupLayout(JFadicionarCurso.getContentPane());
        JFadicionarCurso.getContentPane().setLayout(JFadicionarCursoLayout);
        JFadicionarCursoLayout.setHorizontalGroup(
            JFadicionarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFadicionarCursoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(JFadicionarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnconfirmarAdicao)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JFadicionarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblnomedoCurso)
                        .addComponent(txtnovonomeCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(txtnovaquantidadeAlunos)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        JFadicionarCursoLayout.setVerticalGroup(
            JFadicionarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFadicionarCursoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblnomedoCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnovonomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnovaquantidadeAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnconfirmarAdicao)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jLabel2.setText("Alterar nome");

        jLabel3.setText("Alterar quantidade de alunos");

        txtnovaQtdAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnovaQtdAlunosActionPerformed(evt);
            }
        });

        cbEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um status", "Ativo", "Inativo" }));

        jLabel4.setText("Editar status");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JFeditarCursoLayout = new javax.swing.GroupLayout(JFeditarCurso.getContentPane());
        JFeditarCurso.getContentPane().setLayout(JFeditarCursoLayout);
        JFeditarCursoLayout.setHorizontalGroup(
            JFeditarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFeditarCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JFeditarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JFeditarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtnovoNome)
                        .addComponent(txtnovaQtdAlunos))
                    .addComponent(btnSalvar))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        JFeditarCursoLayout.setVerticalGroup(
            JFeditarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFeditarCursoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnovaQtdAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addComponent(cbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnSalvar)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/image-removebg-preview (2).png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        tbnCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Código", "Status", "Alunos matriculados"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbnCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbnCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbnCursos);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/image-removebg-preview (1).png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/image-removebg-preview.png"))); // NOI18N
        btnExcluri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluriActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/image-removebg-preview (3) (1).png"))); // NOI18N

        txtbarradePesquisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtbarradePesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbarradePesquisaActionPerformed(evt);
            }
        });
        txtbarradePesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbarradePesquisaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtbarradePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnExcluri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtbarradePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluri, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        JFadicionarCurso.setVisible(true);//tornar frame do curso visícvel
        JFadicionarCurso.setSize(400, 300);
        JFadicionarCurso.setLocationRelativeTo(null);//pondo no meio


    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void tbnCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbnCursosMouseClicked
        itemSelecionado = tbnCursos.getSelectedRow();
    }//GEN-LAST:event_tbnCursosMouseClicked

    private void btnconfirmarAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmarAdicaoActionPerformed

        if (stringUtil.isNullOrEmpty(txtnovonomeCurso.getText())) {
            jOptionPane1.showMessageDialog(null, "Nome do curso não pode ser vazio");
            return;
        }

        if (stringUtil.isNullOrEmpty(txtnovaquantidadeAlunos.getText())) {
            jOptionPane1.showMessageDialog(null, "Quantidade de alunos não pode estar vazia");
            return;
        }

        String comboBox = (String) jComboBox1.getSelectedItem();// parametro para verificar seleçao do status

        if (comboBox.equals("Selecione um status")) {

            jOptionPane1.showMessageDialog(null, "Selecione um status válido");
            return;
        }

        Curso cursoCapsula = new Curso(txtnovonomeCurso.getText(), verificarStatusComboBox(jComboBox1), Integer.parseInt(txtnovaquantidadeAlunos.getText()));

        if (cursoCapsula == null) {

            jOptionPane1.showMessageDialog(null, "Não foi possível adicionar o curso, erro 69");

        }

        adicionarCurso(cursoCapsula);//passandpo para a camada de baixo'Service'

         tableModel.setRowCount(0);
         
         preencherTabela();
        
        limparcaixadeTexto();// reseto todas as caixas de texto
        
        JFadicionarCurso.setVisible(false);//ao confirmar envio do curso, fechar a janela
    }//GEN-LAST:event_btnconfirmarAdicaoActionPerformed

    private void btnExcluriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluriActionPerformed
        if (itemSelecionado == -1) {

            jOptionPane1.showMessageDialog(null, "Nenhum curso selecionado tente novamente");
            return;
        }
        Curso cursoExcluir = listaCursos.get(itemSelecionado);

        int resposta = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente excluir o curso:\n" + cursoExcluir.getNome() + "?",
                "Confirmação de exclusão",
                JOptionPane.YES_NO_OPTION
        );
        //0 = sim | 1 = não | -1 = nada
        if (resposta == JOptionPane.YES_OPTION) {
            listaCursos.remove(itemSelecionado);
            tableModel.removeRow(itemSelecionado);
            cursoController.delete(cursoExcluir);

            desfazerSelecao();
        }

    }//GEN-LAST:event_btnExcluriActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       JFeditarCurso.setVisible(true);//tornar frame do curso visícvel
        JFeditarCurso.setSize(400, 300);
        JFeditarCurso.setLocationRelativeTo(null);//pondo no meio
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtnovaQtdAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnovaQtdAlunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnovaQtdAlunosActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       if (listaCursos.isEmpty()) {
            jOptionPane1.showMessageDialog(null, "Nenhum curso cadastrado");
            return;
        }

        if (itemSelecionado == -1) {//item nao selecionado
            jOptionPane1.showMessageDialog(null, "Nenhum curso Selecionado");
            return;
        }

        Curso cursoSelecionado = listaCursos.get(itemSelecionado);

        if (!stringUtil.isNullOrEmpty(txtnovoNome.getText())) {//estando o espaçao vazio manter inalterado

            cursoSelecionado.setNome(txtnovoNome.getText());
        }

        if (!stringUtil.isNullOrEmpty(txtnovaQtdAlunos.getText())) {

            cursoSelecionado.setAlunosMatriculados(Integer.parseInt(txtnovaQtdAlunos.getText()));
        }

        cursoSelecionado.setAtivo(verificarStatusComboBox(cbEditar));

        editarCurso(cursoSelecionado);//atualizar tanto a tabela como o bd e a lisyta

        limparcaixadeTexto();

        JFeditarCurso.setVisible(false);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtbarradePesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbarradePesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbarradePesquisaActionPerformed

    private void txtbarradePesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbarradePesquisaKeyPressed
        if (stringUtil.isNullOrEmpty(txtbarradePesquisa.getText())) {
            //se nao tiver nada mostar tudo
            preencherTabela();
            
        }

        String termo = txtbarradePesquisa.getText().trim();
        tableModel.setRowCount(0);

        try {
            //tenta procurar pelo ID
            Long id = Long.parseLong(termo);
            Curso curso = cursoController.findById(id);

            if (curso == null) {
                tableModel.addRow(new Object[]{
                    curso.getNome(),
                    curso.getId(),
                    formatarStatus(curso.getAtivo()),
                    curso.getAlunosMatriculados()
                });
            } else {
                jOptionPane1.showMessageDialog(null, "Nenhum curso encontrado com esse ID.");
            }
        } catch (NumberFormatException e) {
            //se não for número, pesquisa por nome
            List<Curso> resultados = cursoController.findByName(termo);

            if (resultados.isEmpty()) {// se a lista de resultados estiver vazia lança essa exceção
                jOptionPane1.showMessageDialog(null, "Nenhum curso encontrado com esse nome.");
                 preencherTabela();
                
            } else {
                for (Curso curso : resultados) {
                    tableModel.addRow(new Object[]{
                        curso.getNome(),
                        curso.getId(),
                        formatarStatus(curso.getAtivo()),
                        curso.getAlunosMatriculados() // Método para formatar status
                    });
                }
            }
        }
    }//GEN-LAST:event_txtbarradePesquisaKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame JFadicionarCurso;
    private javax.swing.JFrame JFeditarCurso;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluri;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnconfirmarAdicao;
    private javax.swing.JComboBox<String> cbEditar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblnomedoCurso;
    private javax.swing.JTable tbnCursos;
    private javax.swing.JTextField txtbarradePesquisa;
    private javax.swing.JTextField txtnovaQtdAlunos;
    private javax.swing.JTextField txtnovaquantidadeAlunos;
    private javax.swing.JTextField txtnovoNome;
    private javax.swing.JTextField txtnovonomeCurso;
    // End of variables declaration//GEN-END:variables
}
